name: workbook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # START ----- COMMON APP IMPLEMENTATION -----
  # --- flutter ---
  # http requests
  http: ^1.3.0

  # --- firebase  ---
  # basic integration
  firebase_core: ^3.12.1
  # auth
  firebase_auth: ^5.5.1
  # database
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  # push notifications
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  # analytics
  firebase_analytics: ^11.4.4

  # --- architecture related ---
  # fixes androind build apk issue in flutter 3.29.0
  flutter_plugin_android_lifecycle: 2.0.27
  # getit
  injectable: ^2.5.0
  get_it: ^8.0.3
  # riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # --- basic UI ---
  # icons
  cupertino_icons: ^1.0.8
  # overlay when loading
  loader_overlay: ^5.0.0
  # change text
  change_case: ^2.2.0

  # END ----- COMMON APP IMPLEMENTATION -----

  # START ----- APP FEATURES RELATED -----
  # -- upload pics --
  image_picker: ^1.1.2
  
  # -- user's password generation --
  random_password_generator: ^0.2.1
  auto_route: ^9.3.0+1
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  another_flushbar: ^1.12.30
  flutter_localizations:
    sdk: flutter
  intl: any
  cached_network_image: ^3.4.1

  # END ----- APP FEATURES RELATED -----


dev_dependencies:
  # START ----- TEST RELATED -----
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  golden_toolkit: ^0.15.0
  firebase_core_platform_interface: ^5.4.0  # Added for platform-specific interface (mock data in tests)
  # END ----- TEST RELATED -----

  # START ----- COMMON APP IMPLEMENTATION -----

  # --- flutter related ---
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml`
  flutter_lints: ^5.0.0

  # --- code generation ---
  # melos
  melos: ^6.3.2
  # generation runner
  build_runner: ^2.4.14
  # getit
  injectable_generator: ^2.7.0
  # freezed
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  freezed_lint: ^0.0.7
  json_serializable: ^6.9.3
  #custom_lint: ^0.7.3 # 21.02.2025 - removed due to using too much RAM
  rxdart: ^0.28.0
  # generation of app icon (launcher icon)
  flutter_launcher_icons: ^0.14.3
  # auto_route generation
  auto_route_generator: ^9.3.1
  #riverpod lint and generation
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

  # END ----- COMMON APP IMPLEMENTATION -----


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this items_list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # items_list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
