name: workbook_monorepo

packages:
  - apps/**
  - packages/**

# Recommended option for projects with Dart 2.17.0 or greater.
#
# This enables a new mechanism for linking local packages, which integrates
# better with other tooling (e.g. dart tool, flutter tool, IDE plugins) than the
# mechanism currently being used by default. Please read the documentation for
# usePubspecOverrides before enabling this feature.
#
# See https://melos.invertase.dev/getting-started#setup
command:
  bootstrap:
    usePubspecOverrides: true
   # hooks:
    #  post: "dart pub get && cd apps/workbook && flutter gen-l10n && dart pub run build_runner build --delete-conflicting-outputs"

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    description: Run tests across the monorepo
    run: melos exec --dir-exists=test -- "flutter test"

  build-android-prod:
    description: Build Android app for production
    run: flutter build apk --flavor production -t lib/main_production.dart --release

  build-android-dev:
    description: Build the Android app for development
    run: flutter build apk --flavor development -t lib/main_development.dart --release

  build-ios-prod:
    description: Build the iOS app for production
    run: flutter build ios --release

  build-ios-dev:
    description: Build the iOS app for development
    run: flutter build ios --release